---
langs: [fr_FR,en_US,es_ES] 
baseurl: "/"
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
permalink: /404.html
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
- jekyll-seo-tag
exclude:
- vendor
plugins:
- jekyll-seo-tag
title: "Documentation Jeedom"
description: "Ceci est la documentation, lier Ã  la solution domotique Jeedom."
author: "Jeedom"
image: https://www.jeedom.com/site/logo.png
social:
  name: Jeedom-Plugins-Extra
  links:
    - https://github.com/Jeedom-Plugins-Extra/Jeedom-Plugins-Extra
